import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import prisma from "@/lib/db";
import Provider from "./_components/Provider";
import Nav from "./_components/Nav";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  let isAdmin = false;
  if (session && session?.user?.email) {
    isAdmin =
      (
        await prisma.user.findUnique({
          where: { email: session?.user?.email },
          select: { isAdmin: true },
        })
      )?.isAdmin || false;
  }
  return (
    <html lang="en">
      <Provider session={session}>
        <Nav />
        <body className={inter.className}>{children}</body>
        <Footer />
      </Provider>
    </html>
  );
}
